'use client';

import { Database, ref, set, push, onValue, off, get } from 'firebase/database';

export interface WebRTCStreamStats {
  fps: number;
  bitrateKbps: number;
  latencyMs: number;
  resolution: string;
  connectionState: RTCPeerConnectionState | 'idle' | 'failed' | 'connecting' | 'connected';
  iceState: RTCIceConnectionState | 'idle';
  isRelayed: boolean;
}

export interface WebRTCOptions {
  deviceId?: string;
  db: Database | null;
  onStream: (stream: MediaStream) => void;
  onStatsUpdate?: (stats: WebRTCStreamStats) => void;
  onError?: (error: Error) => void;
}

const DEFAULT_ICE_SERVERS: RTCConfiguration = {
  iceServers: [
    { urls: 'stun:stun.l.google.com:19302' },
    { urls: 'stun:stun1.l.google.com:19302' },
    { urls: 'stun:stun2.l.google.com:19302' },
    { urls: 'stun:stun3.l.google.com:19302' },
    {
      urls: 'turn:openrelay.metered.ca:80',
      username: 'openrelayproject',
      credential: 'openrelayproject',
    },
    {
      urls: 'turn:openrelay.metered.ca:443',
      username: 'openrelayproject',
      credential: 'openrelayproject',
    },
    {
      urls: 'turn:openrelay.metered.ca:443?transport=tcp',
      username: 'openrelayproject',
      credential: 'openrelayproject',
    },
    {
      urls: 'turn:global.relay.metered.ca:80',
      username: 'openrelayproject',
      credential: 'openrelayproject',
    },
    {
      urls: 'turn:global.relay.metered.ca:443',
      username: 'openrelayproject',
      credential: 'openrelayproject',
    },
    {
      urls: 'turn:global.relay.metered.ca:443?transport=tcp',
      username: 'openrelayproject',
      credential: 'openrelayproject',
    },
  ],
  iceCandidatePoolSize: 2,
};

export class WebRTCStreamClient {
  private pc: RTCPeerConnection | null = null;
  private db: Database | null = null;
  private deviceId: string;
  private sessionPath: string;
  private onStreamCallback: (stream: MediaStream) => void;
  private onStatsCallback?: (stats: WebRTCStreamStats) => void;
  private onErrorCallback?: (error: Error) => void;
  private answerListenerUnsub: (() => void) | null = null;
  private piCandidatesUnsub: (() => void) | null = null;
  private statsInterval: NodeJS.Timeout | null = null;
  private reconnectTimeout: NodeJS.Timeout | null = null;
  private processedPiCandidates: Set<string> = new Set();
  private prevBytesReceived = 0;
  private prevTimestamp = 0;
  private isConnecting = false;
  private isManuallyStopped = false;

  constructor(options: WebRTCOptions) {
    this.deviceId = options.deviceId || 'pi_agroeye_01';
    this.sessionPath = `webrtc_sessions/${this.deviceId}`;
    this.db = options.db;
    this.onStreamCallback = options.onStream;
    this.onStatsCallback = options.onStatsUpdate;
    this.onErrorCallback = options.onError;
  }

  public setDatabase(db: Database | null) {
    this.db = db;
  }

  public async start(): Promise<void> {
    this.isManuallyStopped = false;
    if (this.isConnecting || (this.pc && this.pc.connectionState === 'connected')) {
      return;
    }

    if (!this.db) {
      console.warn('[WebRTC] Firebase Database instance not available for signaling.');
      this.onErrorCallback?.(new Error('Firebase Database not initialized'));
      return;
    }

    this.stopInternal();
    this.isConnecting = true;
    this.processedPiCandidates.clear();

    try {
      console.log(`[WebRTC] Initializing connection to Raspberry Pi (${this.deviceId})...`);
      this.pc = new RTCPeerConnection(DEFAULT_ICE_SERVERS);

      // Listen for remote video track from Raspberry Pi
      this.pc.ontrack = (event) => {
        console.log('[WebRTC] Received Remote Video Track from Raspberry Pi!', event.streams);
        if (event.streams && event.streams[0]) {
          this.onStreamCallback(event.streams[0]);
        }
      };

      // Handle Trickle ICE Candidates generated by browser
      this.pc.onicecandidate = (event) => {
        if (event.candidate && this.db) {
          const candidateData = {
            candidate: event.candidate.candidate,
            sdpMid: event.candidate.sdpMid || '0',
            sdpMLineIndex: event.candidate.sdpMLineIndex ?? 0,
          };
          const clientCandRef = push(ref(this.db, `${this.sessionPath}/client_candidates`));
          set(clientCandRef, candidateData).catch((err) => {
            console.debug('[WebRTC] Error pushing client ICE candidate:', err);
          });
        }
      };

      this.pc.onconnectionstatechange = () => {
        if (!this.pc) return;
        const state = this.pc.connectionState;
        console.log(`[WebRTC] Connection State -> ${state.toUpperCase()}`);
        if (state === 'connected') {
          this.isConnecting = false;
        } else if (state === 'failed' || state === 'closed') {
          this.isConnecting = false;
          if (state === 'failed' && !this.isManuallyStopped) {
            this.scheduleReconnect(3000);
          }
        }
        this.emitStats();
      };

      this.pc.oniceconnectionstatechange = () => {
        if (!this.pc) return;
        const iceState = this.pc.iceConnectionState;
        console.log(`[WebRTC] ICE Connection State -> ${iceState.toUpperCase()}`);
        if (iceState === 'failed' && !this.isManuallyStopped) {
          this.scheduleReconnect(3000);
        }
        this.emitStats();
      };

      // Add transceiver to receive video stream only
      this.pc.addTransceiver('video', { direction: 'recvonly' });

      // Create Offer
      const offer = await this.pc.createOffer({
        offerToReceiveVideo: true,
        offerToReceiveAudio: false,
      });
      await this.pc.setLocalDescription(offer);

      // Wait for Initial ICE Gathering (so public STUN/TURN candidates are included inside SDP)
      await new Promise<void>((resolve) => {
        if (!this.pc || this.pc.iceGatheringState === 'complete') {
          resolve();
          return;
        }
        const checkState = () => {
          if (!this.pc || this.pc.iceGatheringState === 'complete') {
            if (this.pc) {
              this.pc.removeEventListener('icegatheringstatechange', checkState);
            }
            resolve();
          }
        };
        this.pc.addEventListener('icegatheringstatechange', checkState);
        // Maximum 1.5s gathering timeout so connection is fast
        setTimeout(() => {
          if (this.pc) {
            this.pc.removeEventListener('icegatheringstatechange', checkState);
          }
          resolve();
        }, 1500);
      });

      const fullLocalSdp = this.pc.localDescription?.sdp || offer.sdp;
      const offerTimestamp = Date.now();
      const offerPayload = {
        sdp: fullLocalSdp,
        type: 'offer',
        timestamp: offerTimestamp,
        client: 'Farmer Mobile App',
      };

      // Reset old candidates in RTDB session
      await set(ref(this.db, `${this.sessionPath}/client_candidates`), null);
      await set(ref(this.db, `${this.sessionPath}/pi_candidates`), null);
      await set(ref(this.db, `${this.sessionPath}/answer`), null);

      // Publish Complete Offer to Firebase Signaling
      await set(ref(this.db, `${this.sessionPath}/offer`), offerPayload);
      console.log('[WebRTC] Offer published to Firebase signaling. Awaiting Pi answer...');

      // 1. Listen for SDP Answer from Raspberry Pi
      const answerRef = ref(this.db, `${this.sessionPath}/answer`);
      this.answerListenerUnsub = onValue(answerRef, async (snapshot) => {
        const answer = snapshot.val();
        if (
          answer &&
          answer.sdp &&
          this.pc &&
          this.pc.signalingState === 'have-local-offer'
        ) {
          console.log('[WebRTC] Received SDP Answer from Raspberry Pi!');
          try {
            await this.pc.setRemoteDescription(
              new RTCSessionDescription({
                sdp: answer.sdp,
                type: answer.type || 'answer',
              })
            );
          } catch (err) {
            console.error('[WebRTC] Failed to set remote description:', err);
          }
        }
      });

      // 2. Listen for Pi ICE Candidates from Firebase
      const piCandRef = ref(this.db, `${this.sessionPath}/pi_candidates`);
      this.piCandidatesUnsub = onValue(piCandRef, async (snapshot) => {
        const val = snapshot.val();
        if (!val || !this.pc) return;

        const candidatesList = Array.isArray(val)
          ? val.filter(Boolean)
          : typeof val === 'object'
          ? Object.values(val)
          : [];

        for (const cand of candidatesList as any[]) {
          if (cand && cand.candidate && !this.processedPiCandidates.has(cand.candidate)) {
            this.processedPiCandidates.add(cand.candidate);
            try {
              await this.pc.addIceCandidate(
                new RTCIceCandidate({
                  candidate: cand.candidate,
                  sdpMid: cand.sdpMid || '0',
                  sdpMLineIndex: cand.sdpMLineIndex ?? 0,
                })
              );
            } catch (err) {
              console.debug('[WebRTC] Error adding Pi candidate:', err);
            }
          }
        }
      });

      // Start periodic WebRTC stats monitoring
      this.startStatsLoop();
    } catch (error: any) {
      this.isConnecting = false;
      console.error('[WebRTC] Connection initiation failed:', error);
      this.onErrorCallback?.(error);
      if (!this.isManuallyStopped) {
        this.scheduleReconnect(4000);
      }
    }
  }

  private scheduleReconnect(delayMs: number) {
    if (this.reconnectTimeout) clearTimeout(this.reconnectTimeout);
    this.reconnectTimeout = setTimeout(() => {
      if (!this.isManuallyStopped && (!this.pc || this.pc.connectionState !== 'connected')) {
        console.log('[WebRTC] Auto-reconnecting to stream...');
        this.start();
      }
    }, delayMs);
  }

  private startStatsLoop() {
    if (this.statsInterval) clearInterval(this.statsInterval);
    this.statsInterval = setInterval(() => {
      this.emitStats();
    }, 1500);
  }

  private async emitStats() {
    if (!this.pc || !this.onStatsCallback) return;

    try {
      const stats = await this.pc.getStats();
      let fps = 0;
      let bitrateKbps = 0;
      let latencyMs = 65;
      let resolution = '640x480';
      let isRelayed = false;

      stats.forEach((report) => {
        if (report.type === 'inbound-rtp' && report.kind === 'video') {
          if (report.framesPerSecond) {
            fps = Math.round(report.framesPerSecond);
          }
          if (report.frameWidth && report.frameHeight) {
            resolution = `${report.frameWidth}x${report.frameHeight}`;
          }
          if (report.bytesReceived && report.timestamp) {
            if (this.prevTimestamp > 0) {
              const bytesDiff = report.bytesReceived - this.prevBytesReceived;
              const timeDiff = (report.timestamp - this.prevTimestamp) / 1000;
              if (timeDiff > 0) {
                bitrateKbps = Math.round((bytesDiff * 8) / (timeDiff * 1024));
              }
            }
            this.prevBytesReceived = report.bytesReceived;
            this.prevTimestamp = report.timestamp;
          }
        }
        if (report.type === 'candidate-pair' && report.state === 'succeeded') {
          if (report.currentRoundTripTime) {
            latencyMs = Math.round(report.currentRoundTripTime * 1000);
          }
        }
        if (report.type === 'local-candidate' || report.type === 'remote-candidate') {
          if (report.candidateType === 'relay') {
            isRelayed = true;
          }
        }
      });

      this.onStatsCallback({
        fps: fps || (this.pc.connectionState === 'connected' ? 20 : 0),
        bitrateKbps,
        latencyMs,
        resolution,
        connectionState: this.pc.connectionState,
        iceState: this.pc.iceConnectionState,
        isRelayed,
      });
    } catch (e) {
      // stats error ignored
    }
  }

  private stopInternal(): void {
    this.isConnecting = false;
    if (this.statsInterval) {
      clearInterval(this.statsInterval);
      this.statsInterval = null;
    }
    if (this.answerListenerUnsub) {
      this.answerListenerUnsub();
      this.answerListenerUnsub = null;
    }
    if (this.piCandidatesUnsub) {
      this.piCandidatesUnsub();
      this.piCandidatesUnsub = null;
    }
    if (this.pc) {
      try {
        this.pc.close();
      } catch (e) {}
      this.pc = null;
    }
    this.prevBytesReceived = 0;
    this.prevTimestamp = 0;
  }

  public stop(): void {
    this.isManuallyStopped = true;
    if (this.reconnectTimeout) {
      clearTimeout(this.reconnectTimeout);
      this.reconnectTimeout = null;
    }
    this.stopInternal();
    console.log('[WebRTC] Stream client stopped.');
  }
}
