import { CropAgronomicProfile, SoilTextureType } from '../types/soilModule';

// ============================================================================
// INDIAN CROP AGRONOMIC & CALENDAR DATABASE (ICAR & FAO-56 Reference)
// ============================================================================

export const CROPS_DATABASE: CropAgronomicProfile[] = [
  {
    id: 'rice_paddy',
    name: 'Rice / Paddy (धान / चावल)',
    nameHi: 'धान / चावल',
    botanicalName: 'Oryza sativa',
    category: 'Cereals',
    primarySeason: 'kharif',
    defaultDurationDays: 125,
    durationRange: [110, 150],
    defaultRootDepthMm: 600,
    rootDepthRangeMm: [400, 800],
    depletionFraction: 0.20, // Low tolerance to soil drying
    totalWaterRequirementMm: [900, 1400],
    tempOptimalRange: [22, 32],
    maturityTerminology: 'Grain maturity (80% golden yellow panicles)',
    maturityTerminologyHi: 'दाने का परिपक्व होना (80% सुनहरी बालियाँ)',
    suitableSoilTypes: ['clay', 'clay_loam', 'alluvial', 'silt_loam', 'black_cotton'],
    growthStages: [
      {
        stage: 'initial',
        name: 'Nursery & Transplanting',
        nameHi: 'नर्सरी व रोपाई',
        durationDays: 25,
        kc: 1.05,
        criticalMoistureSensitivity: 'Critical',
        description: 'Requires standing water layer or saturation for seedling establishment.',
      },
      {
        stage: 'development',
        name: 'Tillering & Vegetative',
        nameHi: 'कल्ले फूटना व वानस्पतिक वृद्धि',
        durationDays: 30,
        kc: 1.15,
        criticalMoistureSensitivity: 'High',
        description: 'Rapid leaf canopy growth and active panicle initiation.',
      },
      {
        stage: 'mid_season',
        name: 'Panicle Heading & Flowering',
        nameHi: 'बाली निकलना व पुष्पन',
        durationDays: 40,
        kc: 1.25,
        criticalMoistureSensitivity: 'Critical',
        description: 'Moisture stress during anthesis causes sterile spikelets and major yield loss.',
      },
      {
        stage: 'late_season',
        name: 'Grain Filling & Ripening',
        nameHi: 'दाना भराव व पकना',
        durationDays: 30,
        kc: 0.90,
        criticalMoistureSensitivity: 'Medium',
        description: 'Gradual field dry-down 10-14 days before harvest.',
      },
    ],
    regionalSowingWindows: [
      {
        region: 'North & Central India (Punjab, Haryana, UP, MP, Rajasthan)',
        startMonth: 6,
        startDay: 15,
        endMonth: 7,
        endDay: 20,
        peakMonth: 7,
        notes: 'Transplanting after monsoon onset in late June to mid-July.',
      },
      {
        region: 'Eastern & Coastal India (WB, Odisha, Bihar, Assam, AP)',
        startMonth: 6,
        startDay: 1,
        endMonth: 7,
        endDay: 30,
        peakMonth: 6,
        notes: 'Aman/Kharif sowing aligned with Bay of Bengal monsoon branch.',
      },
    ],
  },
  {
    id: 'wheat',
    name: 'Wheat (गेहूं)',
    nameHi: 'गेहूं',
    botanicalName: 'Triticum aestivum',
    category: 'Cereals',
    primarySeason: 'rabi',
    defaultDurationDays: 130,
    durationRange: [115, 145],
    defaultRootDepthMm: 900,
    rootDepthRangeMm: [700, 1200],
    depletionFraction: 0.55,
    totalWaterRequirementMm: [450, 650],
    tempOptimalRange: [15, 25],
    maturityTerminology: 'Grain physiological maturity & harvest readiness',
    maturityTerminologyHi: 'दाने की पूर्ण परिपक्वता (कटाव अवस्था)',
    suitableSoilTypes: ['loam', 'clay_loam', 'alluvial', 'sandy_loam', 'black_cotton'],
    growthStages: [
      {
        stage: 'initial',
        name: 'Crown Root Initiation (CRI)',
        nameHi: 'ताज जड़ फुटाव (CRI)',
        durationDays: 22,
        kc: 0.40,
        criticalMoistureSensitivity: 'Critical',
        description: 'CRI stage (20-25 days after sowing) is the most critical irrigation window.',
      },
      {
        stage: 'development',
        name: 'Tillering & Jointing',
        nameHi: 'कल्ले निकलना व गांठे बनना',
        durationDays: 35,
        kc: 0.85,
        criticalMoistureSensitivity: 'High',
        description: 'Stem elongation and head formation inside flag leaf.',
      },
      {
        stage: 'mid_season',
        name: 'Booting, Heading & Flowering',
        nameHi: 'पुष्पन व दुग्धावस्था',
        durationDays: 45,
        kc: 1.15,
        criticalMoistureSensitivity: 'Critical',
        description: 'Pollination and milky grain stage; susceptible to terminal heat stress.',
      },
      {
        stage: 'late_season',
        name: 'Dough Stage & Grain Ripening',
        nameHi: 'दाना भराव व पकना',
        durationDays: 28,
        kc: 0.45,
        criticalMoistureSensitivity: 'Low',
        description: 'Grain hardens and moisture drops below 14% for harvest.',
      },
    ],
    regionalSowingWindows: [
      {
        region: 'North-Western Plains (Punjab, Haryana, West UP, Rajasthan)',
        startMonth: 10,
        startDay: 25,
        endMonth: 11,
        endDay: 25,
        peakMonth: 11,
        notes: 'Optimal sowing when daily mean temperature drops to 20-22°C (first half of November).',
      },
      {
        region: 'Central & Peninsular Zone (MP, Gujarat, Maharashtra, Karnataka)',
        startMonth: 11,
        startDay: 1,
        endMonth: 12,
        endDay: 10,
        peakMonth: 11,
        notes: 'Timely sowing avoids early spring terminal heat.',
      },
    ],
  },
  {
    id: 'maize',
    name: 'Maize / Corn (मक्का)',
    nameHi: 'मक्का',
    botanicalName: 'Zea mays',
    category: 'Cereals',
    primarySeason: 'kharif',
    defaultDurationDays: 100,
    durationRange: [85, 115],
    defaultRootDepthMm: 800,
    rootDepthRangeMm: [600, 1000],
    depletionFraction: 0.50,
    totalWaterRequirementMm: [450, 600],
    tempOptimalRange: [20, 30],
    maturityTerminology: 'Cob black-layer physiological maturity',
    maturityTerminologyHi: 'भुट्टे में काले बिंदु का बनना (पूर्ण परिपक्वता)',
    suitableSoilTypes: ['sandy_loam', 'loam', 'silt_loam', 'clay_loam', 'red_soil', 'alluvial'],
    growthStages: [
      {
        stage: 'initial',
        name: 'Germination & Seedling',
        nameHi: 'अंकुरण व प्रारंभिक पौध',
        durationDays: 20,
        kc: 0.40,
        criticalMoistureSensitivity: 'Medium',
        description: 'Requires aerated, well-drained seedbed with adequate warmth.',
      },
      {
        stage: 'development',
        name: 'Knee-high to Tasseling',
        nameHi: 'वानस्पतिक व मंजरी निकलना',
        durationDays: 30,
        kc: 0.85,
        criticalMoistureSensitivity: 'High',
        description: 'Rapid dry matter accumulation and tassel emergence.',
      },
      {
        stage: 'mid_season',
        name: 'Silking, Pollination & Blister',
        nameHi: 'सिल्क निकलना व परागण',
        durationDays: 30,
        kc: 1.20,
        criticalMoistureSensitivity: 'Critical',
        description: 'Moisture deficit during silking leads to barren ears and severe yield decline.',
      },
      {
        stage: 'late_season',
        name: 'Dough & Cob Maturity',
        nameHi: 'दाना भराव व पकना',
        durationDays: 20,
        kc: 0.60,
        criticalMoistureSensitivity: 'Low',
        description: 'Husk turns brown and kernel moisture declines.',
      },
    ],
    regionalSowingWindows: [
      {
        region: 'All India Kharif (Rajasthan, MP, Karnataka, Bihar, Telangana)',
        startMonth: 6,
        startDay: 15,
        endMonth: 7,
        endDay: 15,
        peakMonth: 7,
        notes: 'Sowing with first soaking monsoon rains (50-75 mm cumulative rainfall).',
      },
    ],
  },
  {
    id: 'cotton',
    name: 'Cotton (कपास)',
    nameHi: 'कपास',
    botanicalName: 'Gossypium hirsutum',
    category: 'Cash Crops',
    primarySeason: 'kharif',
    defaultDurationDays: 165,
    durationRange: [150, 180],
    defaultRootDepthMm: 1200,
    rootDepthRangeMm: [900, 1500],
    depletionFraction: 0.65, // Deep taproot extracts deep moisture
    totalWaterRequirementMm: [700, 1000],
    tempOptimalRange: [25, 35],
    maturityTerminology: 'Boll opening & burst maturity',
    maturityTerminologyHi: 'टिंडे फटना व कपास चुनाई',
    suitableSoilTypes: ['black_cotton', 'clay_loam', 'alluvial', 'loam'],
    growthStages: [
      {
        stage: 'initial',
        name: 'Emergence & Square Initiation',
        nameHi: 'अंकुरण व कलियाँ बनना',
        durationDays: 30,
        kc: 0.45,
        criticalMoistureSensitivity: 'Medium',
        description: 'Deep taproot establishes; excessive moisture causes damping off.',
      },
      {
        stage: 'development',
        name: 'Squaring to Early Flowering',
        nameHi: 'फूल व कलियों का विकास',
        durationDays: 40,
        kc: 0.75,
        criticalMoistureSensitivity: 'High',
        description: 'Sympodial branch formation and flower opening.',
      },
      {
        stage: 'mid_season',
        name: 'Peak Flowering & Boll Development',
        nameHi: 'पूर्ण पुष्पन व टिंडा विकास',
        durationDays: 55,
        kc: 1.15,
        criticalMoistureSensitivity: 'Critical',
        description: 'High water demand; stress causes square and boll shedding.',
      },
      {
        stage: 'late_season',
        name: 'Boll Opening & Bursting',
        nameHi: 'टिंडे खुलना व चुनाई',
        durationDays: 40,
        kc: 0.65,
        criticalMoistureSensitivity: 'Low',
        description: 'Dry warm weather is required for clean lint quality and picking.',
      },
    ],
    regionalSowingWindows: [
      {
        region: 'North Zone (Punjab, Haryana, North Rajasthan)',
        startMonth: 4,
        startDay: 15,
        endMonth: 5,
        endDay: 25,
        peakMonth: 5,
        notes: 'Pre-monsoon irrigated sowing to escape late bollworm and frost.',
      },
      {
        region: 'Central & South Zone (Maharashtra, Gujarat, Telangana, MP)',
        startMonth: 6,
        startDay: 10,
        endMonth: 7,
        endDay: 15,
        peakMonth: 6,
        notes: 'Rainfed sowing on onset of south-west monsoon in Black Cotton soils.',
      },
    ],
  },
  {
    id: 'soybean',
    name: 'Soybean (सोयाबीन)',
    nameHi: 'सोयाबीन',
    botanicalName: 'Glycine max',
    category: 'Oilseeds',
    primarySeason: 'kharif',
    defaultDurationDays: 95,
    durationRange: [85, 110],
    defaultRootDepthMm: 700,
    rootDepthRangeMm: [500, 900],
    depletionFraction: 0.50,
    totalWaterRequirementMm: [450, 600],
    tempOptimalRange: [22, 30],
    maturityTerminology: 'Pod maturity (95% brown pods & leaf shedding)',
    maturityTerminologyHi: 'फलियों का भूरा पड़ना व पत्तियां झड़ना (कटाई अवस्था)',
    suitableSoilTypes: ['black_cotton', 'clay_loam', 'loam', 'silt_loam'],
    growthStages: [
      {
        stage: 'initial',
        name: 'Germination & Vegetative (V1-V4)',
        nameHi: 'अंकुरण व प्राथमिक वृद्धि',
        durationDays: 20,
        kc: 0.40,
        criticalMoistureSensitivity: 'Medium',
        description: 'Rhizobial nodulation and trifoliate leaf establishment.',
      },
      {
        stage: 'development',
        name: 'Branching & Pre-Flowering',
        nameHi: 'शाखाएं निकलना',
        durationDays: 25,
        kc: 0.80,
        criticalMoistureSensitivity: 'High',
        description: 'Canopy closure and flower bud formation.',
      },
      {
        stage: 'mid_season',
        name: 'Pod Setting & Seed Filling (R3-R6)',
        nameHi: 'फली लगना व दाना भराव',
        durationDays: 30,
        kc: 1.15,
        criticalMoistureSensitivity: 'Critical',
        description: 'Crucial window for seed size and oil accumulation; moisture stress reduces yield drastically.',
      },
      {
        stage: 'late_season',
        name: 'Maturity (R7-R8)',
        nameHi: 'परिपक्वता व कटाई',
        durationDays: 20,
        kc: 0.50,
        criticalMoistureSensitivity: 'Low',
        description: 'Leaves turn yellow and drop; pods turn brownish grey.',
      },
    ],
    regionalSowingWindows: [
      {
        region: 'Central India (MP, Maharashtra, Rajasthan, Karnataka)',
        startMonth: 6,
        startDay: 20,
        endMonth: 7,
        endDay: 15,
        peakMonth: 6,
        notes: 'Sow after at least 75-100 mm cumulative rainfall in soil profile.',
      },
    ],
  },
  {
    id: 'mustard',
    name: 'Mustard / Rapeseed (सरसों / राई)',
    nameHi: 'सरसों / राई',
    botanicalName: 'Brassica juncea',
    category: 'Oilseeds',
    primarySeason: 'rabi',
    defaultDurationDays: 120,
    durationRange: [105, 135],
    defaultRootDepthMm: 800,
    rootDepthRangeMm: [600, 1100],
    depletionFraction: 0.60,
    totalWaterRequirementMm: [300, 400],
    tempOptimalRange: [15, 25],
    maturityTerminology: 'Siliqua pod maturity (75% yellow-brown pods)',
    maturityTerminologyHi: 'फलियों का पीला-भूरा पड़ना (सिलिकुआ परिपक्वता)',
    suitableSoilTypes: ['sandy_loam', 'loam', 'alluvial', 'clay_loam'],
    growthStages: [
      {
        stage: 'initial',
        name: 'Germination & Rosette',
        nameHi: 'अंकुरण व रोजेट अवस्था',
        durationDays: 25,
        kc: 0.35,
        criticalMoistureSensitivity: 'Medium',
        description: 'Seedling establishment and deep taproot initiation.',
      },
      {
        stage: 'development',
        name: 'Stem Elongation & Branching',
        nameHi: 'शाखाएं व तना वृद्धि',
        durationDays: 30,
        kc: 0.70,
        criticalMoistureSensitivity: 'High',
        description: 'First irrigation at 30-35 DAS if conserved soil moisture is low.',
      },
      {
        stage: 'mid_season',
        name: 'Flowering & Pod (Siliqua) Formation',
        nameHi: 'पुष्पन व फली विकास',
        durationDays: 40,
        kc: 1.10,
        criticalMoistureSensitivity: 'Critical',
        description: 'Second critical irrigation stage (55-65 DAS) for maximizing seed and oil content.',
      },
      {
        stage: 'late_season',
        name: 'Seed Filling & Ripening',
        nameHi: 'दाना भराव व पकना',
        durationDays: 25,
        kc: 0.40,
        criticalMoistureSensitivity: 'Low',
        description: 'Leaves wither, pods turn golden yellow.',
      },
    ],
    regionalSowingWindows: [
      {
        region: 'North & West India (Rajasthan, Haryana, UP, MP, Gujarat)',
        startMonth: 10,
        startDay: 1,
        endMonth: 10,
        endDay: 25,
        peakMonth: 10,
        notes: 'First fortnight of October is optimal; prevents aphid damage and high temperature at flowering.',
      },
    ],
  },
  {
    id: 'chickpea_gram',
    name: 'Chickpea / Bengal Gram (चना)',
    nameHi: 'चना',
    botanicalName: 'Cicer arietinum',
    category: 'Pulses',
    primarySeason: 'rabi',
    defaultDurationDays: 110,
    durationRange: [95, 125],
    defaultRootDepthMm: 900,
    rootDepthRangeMm: [700, 1200],
    depletionFraction: 0.65, // Highly drought tolerant
    totalWaterRequirementMm: [250, 350],
    tempOptimalRange: [15, 25],
    maturityTerminology: 'Pod maturity (golden-yellow pods with dry rattling seeds)',
    maturityTerminologyHi: 'फलियों का सूखना व दानों का बजना (कटाई अवस्था)',
    suitableSoilTypes: ['black_cotton', 'clay_loam', 'loam', 'sandy_loam', 'alluvial'],
    growthStages: [
      {
        stage: 'initial',
        name: 'Germination & Seedling',
        nameHi: 'अंकुरण व प्रारंभिक पौध',
        durationDays: 20,
        kc: 0.40,
        criticalMoistureSensitivity: 'Low',
        description: 'Sown on residual soil moisture after Kharif harvest.',
      },
      {
        stage: 'development',
        name: 'Branching & Pre-Flowering',
        nameHi: 'शाखाएं निकलना',
        durationDays: 30,
        kc: 0.75,
        criticalMoistureSensitivity: 'High',
        description: 'Pre-flowering irrigation (45 DAS) boosts pod numbers.',
      },
      {
        stage: 'mid_season',
        name: 'Flowering & Pod Setting',
        nameHi: 'पुष्पन व फली विकास',
        durationDays: 35,
        kc: 1.05,
        criticalMoistureSensitivity: 'Critical',
        description: 'Do not irrigate at peak flowering to avoid flower drop.',
      },
      {
        stage: 'late_season',
        name: 'Grain Hardening & Desiccation',
        nameHi: 'दाना भराव व पकना',
        durationDays: 25,
        kc: 0.35,
        criticalMoistureSensitivity: 'Low',
        description: 'Leaves turn yellowish brown and drop.',
      },
    ],
    regionalSowingWindows: [
      {
        region: 'Central & Western India (MP, Rajasthan, Maharashtra, Karnataka)',
        startMonth: 10,
        startDay: 10,
        endMonth: 11,
        endDay: 15,
        peakMonth: 10,
        notes: 'Mid-October to early November utilizing conserved subsoil moisture.',
      },
    ],
  },
  {
    id: 'groundnut',
    name: 'Groundnut / Peanut (मूंगफली)',
    nameHi: 'मूंगफली',
    botanicalName: 'Arachis hypogaea',
    category: 'Oilseeds',
    primarySeason: 'kharif',
    defaultDurationDays: 115,
    durationRange: [100, 130],
    defaultRootDepthMm: 700,
    rootDepthRangeMm: [500, 900],
    depletionFraction: 0.50,
    totalWaterRequirementMm: [500, 650],
    tempOptimalRange: [24, 32],
    maturityTerminology: 'Pod shell interior darkening (70-80% pods mature)',
    maturityTerminologyHi: 'फली के छिलके का अंदर से गहरा होना (परिपक्वता)',
    suitableSoilTypes: ['sandy_loam', 'loamy_sand', 'red_soil', 'alluvial'],
    growthStages: [
      {
        stage: 'initial',
        name: 'Germination & Early Vegetative',
        nameHi: 'अंकुरण व पौध वृद्धि',
        durationDays: 25,
        kc: 0.40,
        criticalMoistureSensitivity: 'Medium',
        description: 'Requires friable loose topsoil for early root and shoot growth.',
      },
      {
        stage: 'development',
        name: 'Flowering & Pegging (Gynephore)',
        nameHi: 'पुष्पन व सुइयां (Pegs) बनना',
        durationDays: 30,
        kc: 0.80,
        criticalMoistureSensitivity: 'Critical',
        description: 'Pegs enter soil; dry crust prevents peg penetration causing pod failure.',
      },
      {
        stage: 'mid_season',
        name: 'Pod Development & Kernel Filling',
        nameHi: 'फली विकास व दाना भराव',
        durationDays: 40,
        kc: 1.15,
        criticalMoistureSensitivity: 'Critical',
        description: 'Requires adequate soil moisture in top 15 cm zone for kernel filling.',
      },
      {
        stage: 'late_season',
        name: 'Pod Maturity & Shell Hardening',
        nameHi: 'फली पकना व कटाई',
        durationDays: 20,
        kc: 0.60,
        criticalMoistureSensitivity: 'Low',
        description: 'Moist soil facilitates easy harvesting without leaving pods in ground.',
      },
    ],
    regionalSowingWindows: [
      {
        region: 'Major Groundnut Belts (Gujarat, AP, Rajasthan, Tamil Nadu)',
        startMonth: 6,
        startDay: 15,
        endMonth: 7,
        endDay: 15,
        peakMonth: 6,
        notes: 'Sown with monsoon onset in well-drained sandy loam soil.',
      },
    ],
  },
  {
    id: 'pearl_millet_bajra',
    name: 'Pearl Millet / Bajra (बाजरा)',
    nameHi: 'बाजरा',
    botanicalName: 'Pennisetum glaucum',
    category: 'Cereals',
    primarySeason: 'kharif',
    defaultDurationDays: 85,
    durationRange: [75, 95],
    defaultRootDepthMm: 900,
    rootDepthRangeMm: [700, 1200],
    depletionFraction: 0.65, // Extreme drought hardiness
    totalWaterRequirementMm: [250, 350],
    tempOptimalRange: [28, 38],
    maturityTerminology: 'Earhead physiological maturity & grain hardening',
    maturityTerminologyHi: 'सिट्टे का सूखना व दाना पकना (पूर्ण परिपक्वता)',
    suitableSoilTypes: ['sandy', 'loamy_sand', 'sandy_loam', 'alluvial', 'red_soil'],
    growthStages: [
      {
        stage: 'initial',
        name: 'Emergence & Tillering',
        nameHi: 'अंकुरण व कल्ले फूटना',
        durationDays: 18,
        kc: 0.35,
        criticalMoistureSensitivity: 'Low',
        description: 'Extremely fast emergence; thrives in high summer heat.',
      },
      {
        stage: 'development',
        name: 'Stem Elongation to Boot',
        nameHi: 'तना वृद्धि व गोभ अवस्था',
        durationDays: 22,
        kc: 0.70,
        criticalMoistureSensitivity: 'Medium',
        description: 'Tiller development and earhead initiation.',
      },
      {
        stage: 'mid_season',
        name: 'Flowering & Grain Formation',
        nameHi: 'पुष्पन व दाना भराव',
        durationDays: 28,
        kc: 1.05,
        criticalMoistureSensitivity: 'High',
        description: 'Only brief rain shower during flowering secures healthy earheads.',
      },
      {
        stage: 'late_season',
        name: 'Grain Hardening & Desiccation',
        nameHi: 'सिट्टा पकना व कटाई',
        durationDays: 17,
        kc: 0.40,
        criticalMoistureSensitivity: 'Low',
        description: 'Earhead turns greyish brown; ready for harvesting.',
      },
    ],
    regionalSowingWindows: [
      {
        region: 'Arid & Semi-Arid Zone (Rajasthan, Gujarat, Haryana, Maharashtra)',
        startMonth: 6,
        startDay: 25,
        endMonth: 7,
        endDay: 20,
        peakMonth: 7,
        notes: 'Sown immediately after first effective monsoon shower (30 mm+).',
      },
    ],
  },
  {
    id: 'pigeonpea_arhar',
    name: 'Pigeonpea / Arhar / Tur (अरहर / तुअर)',
    nameHi: 'अरहर / तुअर',
    botanicalName: 'Cajanus cajan',
    category: 'Pulses',
    primarySeason: 'kharif',
    defaultDurationDays: 160,
    durationRange: [140, 180],
    defaultRootDepthMm: 1200,
    rootDepthRangeMm: [900, 1500],
    depletionFraction: 0.65,
    totalWaterRequirementMm: [500, 700],
    tempOptimalRange: [24, 34],
    maturityTerminology: 'Pod maturity (80% dry brown pods)',
    maturityTerminologyHi: 'फलियों का भूरा होकर सूखना (कटाई अवस्था)',
    suitableSoilTypes: ['black_cotton', 'loam', 'sandy_loam', 'red_soil', 'alluvial'],
    growthStages: [
      {
        stage: 'initial',
        name: 'Seedling & Early Branching',
        nameHi: 'अंकुरण व प्रारंभिक वृद्धि',
        durationDays: 35,
        kc: 0.40,
        criticalMoistureSensitivity: 'Medium',
        description: 'Slow early vegetative growth while deep taproot establishes.',
      },
      {
        stage: 'development',
        name: 'Active Branching & Canopy Expansion',
        nameHi: 'शाखाएं फैलना',
        durationDays: 45,
        kc: 0.75,
        criticalMoistureSensitivity: 'High',
        description: 'Extensive canopy growth utilizing monsoon moisture.',
      },
      {
        stage: 'mid_season',
        name: 'Flowering & Pod Filling',
        nameHi: 'पुष्पन व फली भराव',
        durationDays: 50,
        kc: 1.15,
        criticalMoistureSensitivity: 'Critical',
        description: 'Flowering occurs post-monsoon; extracts subsoil moisture.',
      },
      {
        stage: 'late_season',
        name: 'Pod Ripening & Drying',
        nameHi: 'फलियां पकना व कटाई',
        durationDays: 30,
        kc: 0.45,
        criticalMoistureSensitivity: 'Low',
        description: 'Leaves drop, pods dry on standing stalks.',
      },
    ],
    regionalSowingWindows: [
      {
        region: 'All India Kharif (Maharashtra, MP, Karnataka, UP, Gujarat)',
        startMonth: 6,
        startDay: 15,
        endMonth: 7,
        endDay: 15,
        peakMonth: 6,
        notes: 'Sown early with monsoon onset for optimal vegetative biomass.',
      },
    ],
  },
  {
    id: 'sugarcane',
    name: 'Sugarcane (गन्ना)',
    nameHi: 'गन्ना',
    botanicalName: 'Saccharum officinarum',
    category: 'Cash Crops',
    primarySeason: 'annual',
    defaultDurationDays: 360,
    durationRange: [300, 420],
    defaultRootDepthMm: 1200,
    rootDepthRangeMm: [900, 1500],
    depletionFraction: 0.50,
    totalWaterRequirementMm: [1500, 2200],
    tempOptimalRange: [25, 35],
    maturityTerminology: 'Cane maturity (Brix sugar reading > 18%)',
    maturityTerminologyHi: 'गन्ने में मिठास / रस परिपक्वता (ब्रिक्स 18%+)',
    suitableSoilTypes: ['alluvial', 'loam', 'clay_loam', 'black_cotton'],
    growthStages: [
      {
        stage: 'initial',
        name: 'Germination & Formative',
        nameHi: 'जमाव व कल्ले निकलना',
        durationDays: 60,
        kc: 0.50,
        criticalMoistureSensitivity: 'High',
        description: 'Sprouting from setts and tiller establishment.',
      },
      {
        stage: 'development',
        name: 'Grand Growth Phase',
        nameHi: 'मुख्य तना व पोरियों का विकास',
        durationDays: 150,
        kc: 1.05,
        criticalMoistureSensitivity: 'Critical',
        description: 'Rapid elongation of internodes requiring high moisture & nutrients.',
      },
      {
        stage: 'mid_season',
        name: 'Peak Biomass & Sugar Accumulation',
        nameHi: 'सुक्रोज संचय अवस्था',
        durationDays: 90,
        kc: 1.25,
        criticalMoistureSensitivity: 'High',
        description: 'Sucrose synthesis in stalks.',
      },
      {
        stage: 'late_season',
        name: 'Ripening & Harvest',
        nameHi: 'गन्ना परिपक्वता व कटाई',
        durationDays: 60,
        kc: 0.70,
        criticalMoistureSensitivity: 'Low',
        description: 'Water withholding 25-30 days before cutting increases sugar content.',
      },
    ],
    regionalSowingWindows: [
      {
        region: 'Sub-Tropical North India (UP, Bihar, Punjab, Haryana)',
        startMonth: 2,
        startDay: 15,
        endMonth: 3,
        endDay: 30,
        peakMonth: 3,
        notes: 'Spring planting (Feb-March) or Autumn planting (Oct).',
      },
      {
        region: 'Tropical Zone (Maharashtra, Tamil Nadu, Karnataka, AP)',
        startMonth: 1,
        startDay: 1,
        endMonth: 3,
        endDay: 15,
        peakMonth: 1,
        notes: 'Suru (Jan-Feb), Adsali (July-Aug), and Pre-seasonal (Oct-Nov).',
      },
    ],
  },
];

// Helper to get crop by ID
export function getCropProfileById(cropId: string): CropAgronomicProfile {
  const found = CROPS_DATABASE.find((c) => c.id === cropId);
  return found || CROPS_DATABASE[0];
}
