import { SoilTextureType } from '../types/soilModule';

export interface DistrictInfo {
  state: string;
  district: string;
  lat: number;
  lng: number;
  defaultLandmark: string;
  primarySoil: SoilTextureType;
}

export const DISTRICT_DATABASE: Record<string, Record<string, DistrictInfo>> = {
  'Rajasthan': {
    'Jaipur': {
      state: 'Rajasthan',
      district: 'Jaipur',
      lat: 26.9124,
      lng: 75.7873,
      defaultLandmark: 'Sanganer',
      primarySoil: 'sandy_loam',
    },
    'Udaipur': {
      state: 'Rajasthan',
      district: 'Udaipur',
      lat: 24.5854,
      lng: 73.7125,
      defaultLandmark: 'Badgaon',
      primarySoil: 'sandy_loam',
    },
    'Jodhpur': {
      state: 'Rajasthan',
      district: 'Jodhpur',
      lat: 26.2389,
      lng: 73.0243,
      defaultLandmark: 'Mandore',
      primarySoil: 'sandy',
    },
    'Bikaner': {
      state: 'Rajasthan',
      district: 'Bikaner',
      lat: 28.0229,
      lng: 73.3119,
      defaultLandmark: 'Beechwal',
      primarySoil: 'sandy',
    },
    'Kota': {
      state: 'Rajasthan',
      district: 'Kota',
      lat: 25.1825,
      lng: 75.8398,
      defaultLandmark: 'Ladpura',
      primarySoil: 'black_cotton',
    },
    'Ajmer': {
      state: 'Rajasthan',
      district: 'Ajmer',
      lat: 26.4499,
      lng: 74.6399,
      defaultLandmark: 'Kishangarh',
      primarySoil: 'sandy_loam',
    },
    'Alwar': {
      state: 'Rajasthan',
      district: 'Alwar',
      lat: 27.5530,
      lng: 76.6346,
      defaultLandmark: 'Tijara',
      primarySoil: 'alluvial',
    },
    'Sikar': {
      state: 'Rajasthan',
      district: 'Sikar',
      lat: 27.6094,
      lng: 75.1398,
      defaultLandmark: 'Fatehpur',
      primarySoil: 'sandy_loam',
    },
    'Barmer': {
      state: 'Rajasthan',
      district: 'Barmer',
      lat: 25.7521,
      lng: 71.3967,
      defaultLandmark: 'Balotra',
      primarySoil: 'sandy',
    },
    'Jaisalmer': {
      state: 'Rajasthan',
      district: 'Jaisalmer',
      lat: 26.9157,
      lng: 70.9083,
      defaultLandmark: 'Pokhran',
      primarySoil: 'sandy',
    },
    'Churu': {
      state: 'Rajasthan',
      district: 'Churu',
      lat: 28.2900,
      lng: 74.9600,
      defaultLandmark: 'Ratangarh',
      primarySoil: 'sandy',
    },
    'Nagaur': {
      state: 'Rajasthan',
      district: 'Nagaur',
      lat: 27.2000,
      lng: 73.7400,
      defaultLandmark: 'Merta',
      primarySoil: 'sandy_loam',
    },
    'Bhilwara': {
      state: 'Rajasthan',
      district: 'Bhilwara',
      lat: 25.3407,
      lng: 74.6313,
      defaultLandmark: 'Mandalgarh',
      primarySoil: 'sandy_loam',
    },
    'Chittorgarh': {
      state: 'Rajasthan',
      district: 'Chittorgarh',
      lat: 24.8887,
      lng: 74.6269,
      defaultLandmark: 'Nimbahera',
      primarySoil: 'clay_loam',
    },
    'Pali': {
      state: 'Rajasthan',
      district: 'Pali',
      lat: 25.7711,
      lng: 73.3234,
      defaultLandmark: 'Sumerpur',
      primarySoil: 'sandy_loam',
    },
    'Tonk': {
      state: 'Rajasthan',
      district: 'Tonk',
      lat: 26.1664,
      lng: 75.7885,
      defaultLandmark: 'Niwai',
      primarySoil: 'alluvial',
    },
    'Baran': {
      state: 'Rajasthan',
      district: 'Baran',
      lat: 25.1011,
      lng: 76.5132,
      defaultLandmark: 'Anta',
      primarySoil: 'black_cotton',
    },
    'Bundi': {
      state: 'Rajasthan',
      district: 'Bundi',
      lat: 25.4415,
      lng: 75.6448,
      defaultLandmark: 'Keshoraipatan',
      primarySoil: 'black_cotton',
    },
    'Jhalawar': {
      state: 'Rajasthan',
      district: 'Jhalawar',
      lat: 24.5973,
      lng: 76.1610,
      defaultLandmark: 'Pirawa',
      primarySoil: 'black_cotton',
    },
    'Bharatpur': {
      state: 'Rajasthan',
      district: 'Bharatpur',
      lat: 27.2152,
      lng: 77.4895,
      defaultLandmark: 'Deeg',
      primarySoil: 'alluvial',
    },
    'Dausa': {
      state: 'Rajasthan',
      district: 'Dausa',
      lat: 26.8933,
      lng: 76.3377,
      defaultLandmark: 'Lalsot',
      primarySoil: 'sandy_loam',
    },
    'Sri Ganganagar': {
      state: 'Rajasthan',
      district: 'Sri Ganganagar',
      lat: 29.9038,
      lng: 73.8772,
      defaultLandmark: 'Suratgarh',
      primarySoil: 'alluvial',
    },
    'Hanumangarh': {
      state: 'Rajasthan',
      district: 'Hanumangarh',
      lat: 29.5817,
      lng: 74.3294,
      defaultLandmark: 'Nohar',
      primarySoil: 'alluvial',
    },
  },
  'Maharashtra': {
    'Nagpur': {
      state: 'Maharashtra',
      district: 'Nagpur',
      lat: 21.1458,
      lng: 79.0882,
      defaultLandmark: 'Katol',
      primarySoil: 'black_cotton',
    },
    'Nashik': {
      state: 'Maharashtra',
      district: 'Nashik',
      lat: 19.9975,
      lng: 73.7898,
      defaultLandmark: 'Niphad',
      primarySoil: 'black_cotton',
    },
    'Pune': {
      state: 'Maharashtra',
      district: 'Pune',
      lat: 18.5204,
      lng: 73.8567,
      defaultLandmark: 'Baramati',
      primarySoil: 'black_cotton',
    },
    'Aurangabad': {
      state: 'Maharashtra',
      district: 'Aurangabad',
      lat: 19.8762,
      lng: 75.3433,
      defaultLandmark: 'Paithan',
      primarySoil: 'black_cotton',
    },
    'Amravati': {
      state: 'Maharashtra',
      district: 'Amravati',
      lat: 20.9374,
      lng: 77.7796,
      defaultLandmark: 'Achalpur',
      primarySoil: 'black_cotton',
    },
    'Solapur': {
      state: 'Maharashtra',
      district: 'Solapur',
      lat: 17.6599,
      lng: 75.9064,
      defaultLandmark: 'Pandharpur',
      primarySoil: 'black_cotton',
    },
    'Kolhapur': {
      state: 'Maharashtra',
      district: 'Kolhapur',
      lat: 16.7050,
      lng: 74.2433,
      defaultLandmark: 'Shirol',
      primarySoil: 'black_cotton',
    },
    'Akola': {
      state: 'Maharashtra',
      district: 'Akola',
      lat: 20.7002,
      lng: 77.0082,
      defaultLandmark: 'Murtizapur',
      primarySoil: 'black_cotton',
    },
    'Latur': {
      state: 'Maharashtra',
      district: 'Latur',
      lat: 18.4088,
      lng: 76.5604,
      defaultLandmark: 'Ausa',
      primarySoil: 'black_cotton',
    },
    'Jalgaon': {
      state: 'Maharashtra',
      district: 'Jalgaon',
      lat: 21.0077,
      lng: 75.5626,
      defaultLandmark: 'Bhusawal',
      primarySoil: 'black_cotton',
    },
    'Ahmednagar': {
      state: 'Maharashtra',
      district: 'Ahmednagar',
      lat: 19.0952,
      lng: 74.7496,
      defaultLandmark: 'Rahata',
      primarySoil: 'black_cotton',
    },
    'Satara': {
      state: 'Maharashtra',
      district: 'Satara',
      lat: 17.6805,
      lng: 74.0183,
      defaultLandmark: 'Karad',
      primarySoil: 'black_cotton',
    },
    'Yavatmal': {
      state: 'Maharashtra',
      district: 'Yavatmal',
      lat: 20.3888,
      lng: 78.1204,
      defaultLandmark: 'Pusad',
      primarySoil: 'black_cotton',
    },
    'Nanded': {
      state: 'Maharashtra',
      district: 'Nanded',
      lat: 19.1383,
      lng: 77.3210,
      defaultLandmark: 'Degloor',
      primarySoil: 'black_cotton',
    },
  },
  'Madhya Pradesh': {
    'Indore': {
      state: 'Madhya Pradesh',
      district: 'Indore',
      lat: 22.7196,
      lng: 75.8577,
      defaultLandmark: 'Sanwer',
      primarySoil: 'black_cotton',
    },
    'Bhopal': {
      state: 'Madhya Pradesh',
      district: 'Bhopal',
      lat: 23.2599,
      lng: 77.4126,
      defaultLandmark: 'Berasia',
      primarySoil: 'black_cotton',
    },
    'Ujjain': {
      state: 'Madhya Pradesh',
      district: 'Ujjain',
      lat: 23.1765,
      lng: 75.7885,
      defaultLandmark: 'Tarana',
      primarySoil: 'black_cotton',
    },
    'Dewas': {
      state: 'Madhya Pradesh',
      district: 'Dewas',
      lat: 22.9676,
      lng: 76.0534,
      defaultLandmark: 'Sonkatch',
      primarySoil: 'black_cotton',
    },
    'Gwalior': {
      state: 'Madhya Pradesh',
      district: 'Gwalior',
      lat: 26.2183,
      lng: 78.1828,
      defaultLandmark: 'Dabra',
      primarySoil: 'alluvial',
    },
    'Jabalpur': {
      state: 'Madhya Pradesh',
      district: 'Jabalpur',
      lat: 23.1815,
      lng: 79.9864,
      defaultLandmark: 'Patan',
      primarySoil: 'clay_loam',
    },
    'Sagar': {
      state: 'Madhya Pradesh',
      district: 'Sagar',
      lat: 23.8388,
      lng: 78.7378,
      defaultLandmark: 'Banda',
      primarySoil: 'black_cotton',
    },
    'Khargone': {
      state: 'Madhya Pradesh',
      district: 'Khargone',
      lat: 21.8257,
      lng: 75.6074,
      defaultLandmark: 'Barwaha',
      primarySoil: 'black_cotton',
    },
    'Dhar': {
      state: 'Madhya Pradesh',
      district: 'Dhar',
      lat: 22.5976,
      lng: 75.2965,
      defaultLandmark: 'Badnawar',
      primarySoil: 'black_cotton',
    },
    'Ratlam': {
      state: 'Madhya Pradesh',
      district: 'Ratlam',
      lat: 23.3315,
      lng: 75.0367,
      defaultLandmark: 'Jaora',
      primarySoil: 'black_cotton',
    },
    'Mandsaur': {
      state: 'Madhya Pradesh',
      district: 'Mandsaur',
      lat: 24.0722,
      lng: 75.0684,
      defaultLandmark: 'Malhargarh',
      primarySoil: 'black_cotton',
    },
    'Sehore': {
      state: 'Madhya Pradesh',
      district: 'Sehore',
      lat: 23.2031,
      lng: 77.0844,
      defaultLandmark: 'Ashta',
      primarySoil: 'black_cotton',
    },
    'Hoshangabad': {
      state: 'Madhya Pradesh',
      district: 'Hoshangabad',
      lat: 22.7533,
      lng: 77.7289,
      defaultLandmark: 'Itarsi',
      primarySoil: 'black_cotton',
    },
  },
  'Gujarat': {
    'Rajkot': {
      state: 'Gujarat',
      district: 'Rajkot',
      lat: 22.3039,
      lng: 70.8022,
      defaultLandmark: 'Gondal',
      primarySoil: 'black_cotton',
    },
    'Ahmedabad': {
      state: 'Gujarat',
      district: 'Ahmedabad',
      lat: 23.0225,
      lng: 72.5714,
      defaultLandmark: 'Sanand',
      primarySoil: 'alluvial',
    },
    'Surat': {
      state: 'Gujarat',
      district: 'Surat',
      lat: 21.1702,
      lng: 72.8311,
      defaultLandmark: 'Bardoli',
      primarySoil: 'black_cotton',
    },
    'Vadodara': {
      state: 'Gujarat',
      district: 'Vadodara',
      lat: 22.3072,
      lng: 73.1812,
      defaultLandmark: 'Padra',
      primarySoil: 'alluvial',
    },
    'Junagadh': {
      state: 'Gujarat',
      district: 'Junagadh',
      lat: 21.5222,
      lng: 70.4579,
      defaultLandmark: 'Keshod',
      primarySoil: 'clay_loam',
    },
    'Bhavnagar': {
      state: 'Gujarat',
      district: 'Bhavnagar',
      lat: 21.7645,
      lng: 72.1519,
      defaultLandmark: 'Mahuva',
      primarySoil: 'black_cotton',
    },
    'Jamnagar': {
      state: 'Gujarat',
      district: 'Jamnagar',
      lat: 22.4707,
      lng: 70.0577,
      defaultLandmark: 'Dhrol',
      primarySoil: 'black_cotton',
    },
    'Mehsana': {
      state: 'Gujarat',
      district: 'Mehsana',
      lat: 23.5880,
      lng: 72.3693,
      defaultLandmark: 'Visnagar',
      primarySoil: 'sandy_loam',
    },
    'Banaskantha': {
      state: 'Gujarat',
      district: 'Banaskantha',
      lat: 24.1724,
      lng: 72.4346,
      defaultLandmark: 'Palanpur',
      primarySoil: 'loamy_sand',
    },
    'Amreli': {
      state: 'Gujarat',
      district: 'Amreli',
      lat: 21.6032,
      lng: 71.2221,
      defaultLandmark: 'Dhari',
      primarySoil: 'black_cotton',
    },
    'Kutch': {
      state: 'Gujarat',
      district: 'Kutch',
      lat: 23.2420,
      lng: 69.6669,
      defaultLandmark: 'Bhuj',
      primarySoil: 'sandy',
    },
    'Patan': {
      state: 'Gujarat',
      district: 'Patan',
      lat: 23.8493,
      lng: 72.1266,
      defaultLandmark: 'Sidhpur',
      primarySoil: 'loamy_sand',
    },
  },
  'Punjab': {
    'Ludhiana': {
      state: 'Punjab',
      district: 'Ludhiana',
      lat: 30.9010,
      lng: 75.8573,
      defaultLandmark: 'Samrala',
      primarySoil: 'alluvial',
    },
    'Amritsar': {
      state: 'Punjab',
      district: 'Amritsar',
      lat: 31.6340,
      lng: 74.8723,
      defaultLandmark: 'Ajnala',
      primarySoil: 'alluvial',
    },
    'Jalandhar': {
      state: 'Punjab',
      district: 'Jalandhar',
      lat: 31.3260,
      lng: 75.5762,
      defaultLandmark: 'Nakodar',
      primarySoil: 'alluvial',
    },
    'Patiala': {
      state: 'Punjab',
      district: 'Patiala',
      lat: 30.3398,
      lng: 76.3869,
      defaultLandmark: 'Nabha',
      primarySoil: 'alluvial',
    },
    'Bathinda': {
      state: 'Punjab',
      district: 'Bathinda',
      lat: 30.2110,
      lng: 74.9455,
      defaultLandmark: 'Talwandi Sabo',
      primarySoil: 'sandy_loam',
    },
    'Sangrur': {
      state: 'Punjab',
      district: 'Sangrur',
      lat: 30.2458,
      lng: 75.8421,
      defaultLandmark: 'Sunam',
      primarySoil: 'alluvial',
    },
    'Ferozepur': {
      state: 'Punjab',
      district: 'Ferozepur',
      lat: 30.9237,
      lng: 74.6114,
      defaultLandmark: 'Zira',
      primarySoil: 'alluvial',
    },
    'Hoshiarpur': {
      state: 'Punjab',
      district: 'Hoshiarpur',
      lat: 31.5273,
      lng: 75.9149,
      defaultLandmark: 'Dasuya',
      primarySoil: 'alluvial',
    },
    'Gurdaspur': {
      state: 'Punjab',
      district: 'Gurdaspur',
      lat: 32.0419,
      lng: 75.4053,
      defaultLandmark: 'Batala',
      primarySoil: 'alluvial',
    },
  },
  'Haryana': {
    'Karnal': {
      state: 'Haryana',
      district: 'Karnal',
      lat: 29.6857,
      lng: 76.9905,
      defaultLandmark: 'Gharaunda',
      primarySoil: 'alluvial',
    },
    'Hisar': {
      state: 'Haryana',
      district: 'Hisar',
      lat: 29.1492,
      lng: 75.7217,
      defaultLandmark: 'Hansi',
      primarySoil: 'sandy_loam',
    },
    'Rohtak': {
      state: 'Haryana',
      district: 'Rohtak',
      lat: 28.8955,
      lng: 76.6066,
      defaultLandmark: 'Meham',
      primarySoil: 'alluvial',
    },
    'Ambala': {
      state: 'Haryana',
      district: 'Ambala',
      lat: 30.3782,
      lng: 76.7767,
      defaultLandmark: 'Barara',
      primarySoil: 'alluvial',
    },
    'Sirsa': {
      state: 'Haryana',
      district: 'Sirsa',
      lat: 29.5349,
      lng: 75.0296,
      defaultLandmark: 'Ellenabad',
      primarySoil: 'sandy_loam',
    },
    'Kurukshetra': {
      state: 'Haryana',
      district: 'Kurukshetra',
      lat: 29.9695,
      lng: 76.8783,
      defaultLandmark: 'Pehowa',
      primarySoil: 'alluvial',
    },
    'Sonipat': {
      state: 'Haryana',
      district: 'Sonipat',
      lat: 28.9931,
      lng: 77.0151,
      defaultLandmark: 'Ganaur',
      primarySoil: 'alluvial',
    },
    'Bhiwani': {
      state: 'Haryana',
      district: 'Bhiwani',
      lat: 28.7831,
      lng: 76.1397,
      defaultLandmark: 'Tosham',
      primarySoil: 'sandy_loam',
    },
    'Fatehabad': {
      state: 'Haryana',
      district: 'Fatehabad',
      lat: 29.5160,
      lng: 75.4530,
      defaultLandmark: 'Tohana',
      primarySoil: 'alluvial',
    },
    'Jind': {
      state: 'Haryana',
      district: 'Jind',
      lat: 29.3160,
      lng: 76.3174,
      defaultLandmark: 'Narwana',
      primarySoil: 'alluvial',
    },
  },
  'Uttar Pradesh': {
    'Varanasi': {
      state: 'Uttar Pradesh',
      district: 'Varanasi',
      lat: 25.3176,
      lng: 82.9739,
      defaultLandmark: 'Pindra',
      primarySoil: 'alluvial',
    },
    'Lucknow': {
      state: 'Uttar Pradesh',
      district: 'Lucknow',
      lat: 26.8467,
      lng: 80.9462,
      defaultLandmark: 'Malihabad',
      primarySoil: 'alluvial',
    },
    'Kanpur': {
      state: 'Uttar Pradesh',
      district: 'Kanpur',
      lat: 26.4499,
      lng: 80.3319,
      defaultLandmark: 'Bilhaur',
      primarySoil: 'alluvial',
    },
    'Agra': {
      state: 'Uttar Pradesh',
      district: 'Agra',
      lat: 27.1767,
      lng: 78.0081,
      defaultLandmark: 'Fatehabad',
      primarySoil: 'alluvial',
    },
    'Meerut': {
      state: 'Uttar Pradesh',
      district: 'Meerut',
      lat: 28.9845,
      lng: 77.7064,
      defaultLandmark: 'Mawana',
      primarySoil: 'alluvial',
    },
    'Prayagraj': {
      state: 'Uttar Pradesh',
      district: 'Prayagraj',
      lat: 25.4358,
      lng: 81.8463,
      defaultLandmark: 'Phulpur',
      primarySoil: 'alluvial',
    },
    'Gorakhpur': {
      state: 'Uttar Pradesh',
      district: 'Gorakhpur',
      lat: 26.7606,
      lng: 83.3732,
      defaultLandmark: 'Sahjanwa',
      primarySoil: 'alluvial',
    },
    'Bareilly': {
      state: 'Uttar Pradesh',
      district: 'Bareilly',
      lat: 28.3670,
      lng: 79.4304,
      defaultLandmark: 'Aonla',
      primarySoil: 'alluvial',
    },
    'Aligarh': {
      state: 'Uttar Pradesh',
      district: 'Aligarh',
      lat: 27.8974,
      lng: 78.0880,
      defaultLandmark: 'Atrauli',
      primarySoil: 'alluvial',
    },
    'Moradabad': {
      state: 'Uttar Pradesh',
      district: 'Moradabad',
      lat: 28.8386,
      lng: 78.7733,
      defaultLandmark: 'Bilari',
      primarySoil: 'alluvial',
    },
    'Ayodhya': {
      state: 'Uttar Pradesh',
      district: 'Ayodhya',
      lat: 26.7922,
      lng: 82.1998,
      defaultLandmark: 'Rudauli',
      primarySoil: 'alluvial',
    },
    'Jhansi': {
      state: 'Uttar Pradesh',
      district: 'Jhansi',
      lat: 25.4484,
      lng: 78.5685,
      defaultLandmark: 'Mauranipur',
      primarySoil: 'black_cotton',
    },
  },
  'Karnataka': {
    'Belagavi': {
      state: 'Karnataka',
      district: 'Belagavi',
      lat: 15.8497,
      lng: 74.4977,
      defaultLandmark: 'Gokak',
      primarySoil: 'black_cotton',
    },
    'Dharwad': {
      state: 'Karnataka',
      district: 'Dharwad',
      lat: 15.4589,
      lng: 75.0078,
      defaultLandmark: 'Hubballi',
      primarySoil: 'black_cotton',
    },
    'Mysuru': {
      state: 'Karnataka',
      district: 'Mysuru',
      lat: 12.2958,
      lng: 76.6394,
      defaultLandmark: 'Nanjangud',
      primarySoil: 'red_soil',
    },
    'Ballari': {
      state: 'Karnataka',
      district: 'Ballari',
      lat: 15.1394,
      lng: 76.9214,
      defaultLandmark: 'Siruguppa',
      primarySoil: 'black_cotton',
    },
    'Kalaburagi': {
      state: 'Karnataka',
      district: 'Kalaburagi',
      lat: 17.3297,
      lng: 76.8343,
      defaultLandmark: 'Sedam',
      primarySoil: 'black_cotton',
    },
    'Vijayapura': {
      state: 'Karnataka',
      district: 'Vijayapura',
      lat: 16.8302,
      lng: 75.7100,
      defaultLandmark: 'Indi',
      primarySoil: 'black_cotton',
    },
    'Shivamogga': {
      state: 'Karnataka',
      district: 'Shivamogga',
      lat: 13.9299,
      lng: 75.5681,
      defaultLandmark: 'Bhadravathi',
      primarySoil: 'red_soil',
    },
    'Tumakuru': {
      state: 'Karnataka',
      district: 'Tumakuru',
      lat: 13.3379,
      lng: 77.1010,
      defaultLandmark: 'Tiptur',
      primarySoil: 'red_soil',
    },
    'Mandya': {
      state: 'Karnataka',
      district: 'Mandya',
      lat: 12.5218,
      lng: 76.8951,
      defaultLandmark: 'Maddur',
      primarySoil: 'red_soil',
    },
    'Raichur': {
      state: 'Karnataka',
      district: 'Raichur',
      lat: 16.2076,
      lng: 77.3463,
      defaultLandmark: 'Sindhanur',
      primarySoil: 'black_cotton',
    },
  },
  'Tamil Nadu': {
    'Coimbatore': {
      state: 'Tamil Nadu',
      district: 'Coimbatore',
      lat: 11.0168,
      lng: 76.9558,
      defaultLandmark: 'Pollachi',
      primarySoil: 'red_soil',
    },
    'Madurai': {
      state: 'Tamil Nadu',
      district: 'Madurai',
      lat: 9.9252,
      lng: 78.1198,
      defaultLandmark: 'Melur',
      primarySoil: 'red_soil',
    },
    'Tiruchirappalli': {
      state: 'Tamil Nadu',
      district: 'Tiruchirappalli',
      lat: 10.7905,
      lng: 78.7047,
      defaultLandmark: 'Lalgudi',
      primarySoil: 'alluvial',
    },
    'Salem': {
      state: 'Tamil Nadu',
      district: 'Salem',
      lat: 11.6643,
      lng: 78.1460,
      defaultLandmark: 'Attur',
      primarySoil: 'red_soil',
    },
    'Thanjavur': {
      state: 'Tamil Nadu',
      district: 'Thanjavur',
      lat: 10.7870,
      lng: 79.1378,
      defaultLandmark: 'Kumbakonam',
      primarySoil: 'alluvial',
    },
    'Erode': {
      state: 'Tamil Nadu',
      district: 'Erode',
      lat: 11.3410,
      lng: 77.7172,
      defaultLandmark: 'Gobichettipalayam',
      primarySoil: 'red_soil',
    },
    'Tirunelveli': {
      state: 'Tamil Nadu',
      district: 'Tirunelveli',
      lat: 8.7139,
      lng: 77.7567,
      defaultLandmark: 'Ambasamudram',
      primarySoil: 'red_soil',
    },
    'Dindigul': {
      state: 'Tamil Nadu',
      district: 'Dindigul',
      lat: 10.3673,
      lng: 77.9803,
      defaultLandmark: 'Palani',
      primarySoil: 'red_soil',
    },
    'Vellore': {
      state: 'Tamil Nadu',
      district: 'Vellore',
      lat: 12.9165,
      lng: 79.1325,
      defaultLandmark: 'Gudiyatham',
      primarySoil: 'red_soil',
    },
  },
  'Telangana': {
    'Hyderabad': {
      state: 'Telangana',
      district: 'Hyderabad',
      lat: 17.3850,
      lng: 78.4867,
      defaultLandmark: 'Shamshabad',
      primarySoil: 'red_soil',
    },
    'Warangal': {
      state: 'Telangana',
      district: 'Warangal',
      lat: 17.9689,
      lng: 79.5941,
      defaultLandmark: 'Jangaon',
      primarySoil: 'red_soil',
    },
    'Nizamabad': {
      state: 'Telangana',
      district: 'Nizamabad',
      lat: 18.6725,
      lng: 78.0941,
      defaultLandmark: 'Armoor',
      primarySoil: 'black_cotton',
    },
    'Karimnagar': {
      state: 'Telangana',
      district: 'Karimnagar',
      lat: 18.4386,
      lng: 79.1288,
      defaultLandmark: 'Huzurabad',
      primarySoil: 'red_soil',
    },
    'Khammam': {
      state: 'Telangana',
      district: 'Khammam',
      lat: 17.2473,
      lng: 80.1514,
      defaultLandmark: 'Madhira',
      primarySoil: 'alluvial',
    },
    'Nalgonda': {
      state: 'Telangana',
      district: 'Nalgonda',
      lat: 17.0575,
      lng: 79.2684,
      defaultLandmark: 'Miryalaguda',
      primarySoil: 'red_soil',
    },
    'Mahabubnagar': {
      state: 'Telangana',
      district: 'Mahabubnagar',
      lat: 16.7488,
      lng: 77.9856,
      defaultLandmark: 'Jadcherla',
      primarySoil: 'red_soil',
    },
    'Adilabad': {
      state: 'Telangana',
      district: 'Adilabad',
      lat: 19.6641,
      lng: 78.5320,
      defaultLandmark: 'Utnoor',
      primarySoil: 'black_cotton',
    },
  },
  'Bihar': {
    'Patna': {
      state: 'Bihar',
      district: 'Patna',
      lat: 25.5941,
      lng: 85.1376,
      defaultLandmark: 'Danapur',
      primarySoil: 'alluvial',
    },
    'Gaya': {
      state: 'Bihar',
      district: 'Gaya',
      lat: 24.7914,
      lng: 85.0002,
      defaultLandmark: 'Bodh Gaya',
      primarySoil: 'alluvial',
    },
    'Bhagalpur': {
      state: 'Bihar',
      district: 'Bhagalpur',
      lat: 25.2425,
      lng: 86.9842,
      defaultLandmark: 'Kahalgaon',
      primarySoil: 'alluvial',
    },
    'Muzaffarpur': {
      state: 'Bihar',
      district: 'Muzaffarpur',
      lat: 26.1226,
      lng: 85.3906,
      defaultLandmark: 'Kanti',
      primarySoil: 'alluvial',
    },
    'Purnia': {
      state: 'Bihar',
      district: 'Purnia',
      lat: 25.7771,
      lng: 87.4753,
      defaultLandmark: 'Banmankhi',
      primarySoil: 'silt_loam',
    },
    'Darbhanga': {
      state: 'Bihar',
      district: 'Darbhanga',
      lat: 26.1542,
      lng: 85.8918,
      defaultLandmark: 'Benipur',
      primarySoil: 'alluvial',
    },
    'Samastipur': {
      state: 'Bihar',
      district: 'Samastipur',
      lat: 25.8631,
      lng: 85.7811,
      defaultLandmark: 'Pusa',
      primarySoil: 'alluvial',
    },
    'Rohtas': {
      state: 'Bihar',
      district: 'Rohtas',
      lat: 24.9546,
      lng: 84.0150,
      defaultLandmark: 'Sasaram',
      primarySoil: 'alluvial',
    },
    'Begusarai': {
      state: 'Bihar',
      district: 'Begusarai',
      lat: 25.4182,
      lng: 86.1272,
      defaultLandmark: 'Barauni',
      primarySoil: 'alluvial',
    },
  },
  'West Bengal': {
    'Bardhaman': {
      state: 'West Bengal',
      district: 'Bardhaman',
      lat: 23.2324,
      lng: 87.8615,
      defaultLandmark: 'Kalna',
      primarySoil: 'alluvial',
    },
    'Murshidabad': {
      state: 'West Bengal',
      district: 'Murshidabad',
      lat: 24.1759,
      lng: 88.2802,
      defaultLandmark: 'Berhampore',
      primarySoil: 'alluvial',
    },
    'Nadia': {
      state: 'West Bengal',
      district: 'Nadia',
      lat: 23.4710,
      lng: 88.5565,
      defaultLandmark: 'Ranaghat',
      primarySoil: 'alluvial',
    },
    'Hooghly': {
      state: 'West Bengal',
      district: 'Hooghly',
      lat: 22.9039,
      lng: 88.3968,
      defaultLandmark: 'Singur',
      primarySoil: 'alluvial',
    },
    'Midnapore': {
      state: 'West Bengal',
      district: 'Midnapore',
      lat: 22.4257,
      lng: 87.3199,
      defaultLandmark: 'Kharagpur',
      primarySoil: 'alluvial',
    },
    'Birbhum': {
      state: 'West Bengal',
      district: 'Birbhum',
      lat: 23.8404,
      lng: 87.6186,
      defaultLandmark: 'Bolpur',
      primarySoil: 'red_soil',
    },
    'Malda': {
      state: 'West Bengal',
      district: 'Malda',
      lat: 25.0108,
      lng: 88.1411,
      defaultLandmark: 'English Bazar',
      primarySoil: 'silt_loam',
    },
    'Bankura': {
      state: 'West Bengal',
      district: 'Bankura',
      lat: 23.2319,
      lng: 87.0784,
      defaultLandmark: 'Bishnupur',
      primarySoil: 'red_soil',
    },
  },
};

/**
 * Get district coordinates, default landmark, and regional soil
 */
export function getDistrictDetails(stateName: string, districtName: string): DistrictInfo {
  const stateDistricts = DISTRICT_DATABASE[stateName];
  if (stateDistricts && stateDistricts[districtName]) {
    return stateDistricts[districtName];
  }

  // Fallback defaults if district not found in pre-mapped table
  return {
    state: stateName,
    district: districtName,
    lat: 26.9124,
    lng: 75.7873,
    defaultLandmark: districtName,
    primarySoil: 'sandy_loam',
  };
}

/**
 * Get all districts for a given state
 */
export function getDistrictsForState(stateName: string): string[] {
  const stateDistricts = DISTRICT_DATABASE[stateName];
  if (stateDistricts) {
    return Object.keys(stateDistricts);
  }
  return ['Central District', 'North Sector', 'South Sector'];
}
